language: node_js
node_js:
- '10'
deploy:
  provider: heroku
  api_key:
    secure: bISTJOysqEn72ExuphonN/7KW716YmUph4vr9RW4tonccQI5Za6giqnQcic+2/0Y3zcZymqSeVKJvT46wWd9ctYFZDd8zllTnj7CPGYtobDUw7EyuN3en982rx9WSnY7CVY2g42gG1jrBax7zGl5DAzBGH3zhzmcKNEhqm45+1xVoDzw5sFZ+fhjh8W5spYyKmY4AjztAFvsV8HgNBcBPGnD25L7kiBgolYRrtuHWpVjmu1dBNccR4I9cetOCgUk7INwWC6su2Gonep8KLOwBn8ZVZ6m1yvGG0FE0jAdkqdq8HMNJSQ4gux73luEXDXNXTdLXER1X8hj3RjiX3rY9rQox6Lij7axqB6xk97J2M35BDD32xG3UAXXn0qj/i+e18Hkdah4YajMp7JxYYr7gsQ5Sab1WZsYFXaMof4Mnt3oShT6tEwAp92xgW9PGqSdK+DtQIO/AA0e0e1r6o6pG1AxSygzA5LYg7Lt6gtUFBetb37dXsMrGLedREixyTy+/DTLUL2NlNNfCSBdXuky9VxoT1YEVGnk6t53SuJkpgPS0dXte9IvZ0QszVrWs7gKhSt1FP/K7YYKWhuFdj6OmDLkcw0IZlTx+0FX2Cp8qjCeDdmO2J4paCeEyyCKcVTcb4SmFzD/2d0zs9eEEMnWY3ivz20GPg/mZfSGQ+3jxwQ=
  app: protected-sea-34899
  on:
    branch: master
